export const getGreetingMessage = (studentName, timeOfDay) => {
    const firstName = studentName?.split(' ')[0] || 'Şampiyon';
    
    // 100 unique motivational greetings
    const greetings = [
        "Bugün harikalar yaratmaya hazır mısın? Hedeflerine bir adım daha yaklaş.",
        "Başarı, her gün atılan küçük adımların toplamıdır. Bugün o adımı at!",
        "Zorluklar seni yıldırmasın, onlar sadece ne kadar güçlü olduğunu gösterir.",
        "Hayallerine giden yolda bugün yeni bir sayfa açıyoruz.",
        "Potansiyelinin sınırlarını zorlama vakti geldi.",
        "Gelecekteki sen, bugünkü sana teşekkür edecek.",
        "Kendine inan; çünkü biz sana çok inanıyoruz.",
        "Başlamak için mükemmel olmayı bekleme, mükemmel olmak için başla.",
        "Her yeni gün, yeni bir şanstır. Bu şansı iyi değerlendir.",
        "Çalışkanlık zekayı yener. Bugün çalışkanlık günün olsun.",
        "Hedefine giden yolda engeller olacak, ama sen onları aşmak için buradasın.",
        "Sınırlar sadece zihnindedir. Onları bugün yık!",
        "Her deneme bir tecrübe, her tecrübe bir basamaktır.",
        "Düşlerin, eylemlerin kadar büyüktür.",
        "Bugün dünden daha iyisi olmak senin elinde.",
        "Büyük başarılar, pes etmeyenlerin eseridir.",
        "Başarı bir varış noktası değil, bir yolculuktur. Yolculuğun tadını çıkar.",
        "İçindeki gücü keşfet ve onu bugün serbest bırak.",
        "Geleceği tahmin etmenin en iyi yolu onu inşa etmektir.",
        "Yorulabilirsin ama asla pes etme.",
        "Bugünün çabası, yarının rahatlığıdır.",
        "Zirveye giden yol düz değildir, ama manzara buna değer.",
        "Kendi hikayenin kahramanı sen ol.",
        "Bir hayal ile bir hedef arasındaki fark, eylemdir.",
        "Ertelemeyi bırak, eyleme geç. Zaman şimdi!",
        "Yapabileceğine inandığın an, yarısını başarmışsındır.",
        "Düşmek başarısızlık değildir, kalkmamak başarısızlıktır.",
        "Kararlı ol, odaklan ve bugün harika işler çıkar.",
        "Büyük işler başarmak için büyük düşünmelisin.",
        "Senin çaban, senin başarın demektir.",
        "Bugün, dünden daha iyi bir sen yaratmak için mükemmel bir gün.",
        "Zamanını iyi yönetirsen, hayatını da iyi yönetirsin.",
        "Başarı tesadüf değildir; çok çalışmanın, öğrenmenin ve azmin sonucudur.",
        "Hedefine odaklan, gerisi teferruattır.",
        "Korkularının seni durdurmasına izin verme.",
        "Bugün atacağın küçük bir adım, yarınki büyük bir sıçrayışın başlangıcı olabilir.",
        "En iyi yatırım, kendine yaptığın yatırımdır.",
        "Öğrenmeye açık ol, çünkü bilgi en büyük güçtür.",
        "Pes ettiğin an, kaybettiğin andır. Devam et!",
        "Hayallerin için savaşmaya değer.",
        "Başarı, engellere rağmen ilerleyebilme yeteneğidir.",
        "Bugün kendini aşma günün olsun.",
        "Küçük ilerlemeler, büyük sonuçlar doğurur.",
        "Zihnini hedefine odakla, bedenin onu takip edecektir.",
        "Bahaneler seni hedeflerinden uzaklaştırır. Bahanelere yer yok!",
        "Her yeni bilgi, hedefine giden yolda bir ışıktır.",
        "İçindeki ışığı dışarı yansıt ve etrafını aydınlat.",
        "Kendine meydan oku ve neler başarabileceğini gör.",
        "Başarı, hazırlıkla fırsatın karşılaştığı yerdir.",
        "Bugün kendi rekorunu kırma günün.",
        "Gelecek, ona bugünden hazırlananlarındır.",
        "Kararlılık, başarının anahtarıdır.",
        "Kendine olan inancın, en güçlü silahındır.",
        "Zorluklar, karakterini şekillendiren fırsatlardır.",
        "Daima ileriye bak, çünkü hedeflerin orada seni bekliyor.",
        "Bugün öğren, yarın yönet.",
        "Sürekli gelişim, kalıcı başarının sırrıdır.",
        "Fark yaratmak için farklı düşün.",
        "Hayallerini gerçeğe dönüştürme gücü senin ellerinde.",
        "Başarı, doğru alışkanlıkların eseridir.",
        "Azim ve sabır, her kapıyı açar.",
        "Zaman su gibi akıp geçiyor, onu hedeflerin için kullan.",
        "En büyük zafer, kendi kendini yenmektir.",
        "Her soru bir adımdır, her cevap bir basamak.",
        "Öğrenmek hiçbir zaman aklı yormaz.",
        "Başarının sırrı, ne istediğini bilmekte yatar.",
        "Hayat bir sınavdır, ama sen bu sınav için çalışıyorsun.",
        "Kendi yolunu kendin çiz.",
        "Engeller sadece odaklanman gereken yeri gösterir.",
        "Büyük başarılar zaman alır, sabırlı ol.",
        "Kendine dürüst ol ve hedeflerinden sapma.",
        "Bugün attığın tohumlar, yarınki başarı ormanın olacak.",
        "Pes etmek bir seçenek değil.",
        "Öğrenmenin yaşı ve sınırı yoktur.",
        "İstikrar, yetenekten daha önemlidir.",
        "Başarıya giden asansör bozuktur, merdivenleri kullanmalısın.",
        "Motivasyon seni başlatır, alışkanlıklar devam etmeni sağlar.",
        "Her gün biraz daha iyiye, biraz daha ileriye.",
        "Fırsatlar sen onları yarattığında ortaya çıkar.",
        "Kendini sadece dünkü kendinle kıyasla.",
        "Bilgi birikimi, geleceğinin teminatıdır.",
        "Zor olan, güzel olanın habercisidir.",
        "Hayallerinin peşinden koşacak cesareti bul.",
        "Bugünün işini yarına bırakma, çünkü yarın yeni hedefler var.",
        "Başarı, rahatlık alanının dışında başlar.",
        "Zihnini sınırlandırma, potansiyelini serbest bırak.",
        "Kendine güven ve adımlarını sağlam at.",
        "Her hata, yeni bir öğrenme fırsatıdır.",
        "Başarı, pes etmeyenlerin ödülüdür.",
        "Odaklan, çalış, başar. Bu formül hiç şaşmaz.",
        "Bugün bir fark yarat.",
        "İmkansız sadece bir kelimedir.",
        "Kendin için en iyisini iste ve bunun için çalış.",
        "Yolun neresinde olursan ol, daima ileriye doğru yürü.",
        "Bilgi, karanlığı aydınlatan tek ışıktır.",
        "Kararlı adımlarla hedefine yürü.",
        "Senin hikayen daha yeni başlıyor, onu en güzel şekilde yaz.",
        "Başarı, çabalarının yankısıdır.",
        "Unutma, sen bundan daha fazlasısın!"
    ];

    // Pick a random message
    const randomMessage = greetings[Math.floor(Math.random() * greetings.length)];

    return {
        title: `${timeOfDay}, ${firstName}! 👋`,
        message: randomMessage
    };
};
